### ISSUE TITLE
Running SABThrottle

### ISSUE THREAD

**Issue by jschollenberger** [kylerw/SABThrottle#1]
Thanks for writing this script; it's a really great idea! I took it and forked it to better fit my needs if you're interested:

https://github.com/compywiz/SABThrottle

I'm just curious as to how you run your script? I was hoping for there to be a way for Plex or SABnzbd to actually call it on events (stream, download started/stopped, etc), but didn't see any right off the bat. Otherwise, I suppose an every minute cron would do the trick.

**Comment by jschollenberger** [comment]
Almost a year later, I decided to rip this out of cron and put it into plexWatch where it belongs. I wanted to post it here in case you/others are interested. It's pretty simple, just add the following to your external section:

        'SABThrottle' =>        {
            'enabled'       => 1, ## 0 or 1 - set to 1 to enable homeAutomation script
            'push_watched'  => 1, #stop
            'push_watching' => 1, #start
            'push_paused'   => 1, #pause
            'push_resumed'  => 1, #resume

            'script_format' => {
                'start'   =>  '/path/to/SABThrottle.py',
                'paused'  =>  '/path/to/SABThrottle.py',
                'resumed' =>  '/path/to/SABThrottle.py',
                'stop'    =>  '/path/to/e/SABThrottle.py',
            },
        },

The only downside that came to light when doing this is that since SABThrottle only checks the size of the MediaContainer, it can't tell that one may be paused and therefore throttle you for no reason for the lifetime of the pause.

**Comment by kylerw** [comment]
Awesome work! Glad to see you are still getting some use from this. I've since moved to NZBGet and haven't taken the time to adapt it just yet.
